### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by dvdsk** [danieldg/rwaybar#2]
Hi there, first of all thanks for building a fast zero dependency Wayland compatible bar with excellent documentation in the wiki.

When I started using rwaybar I copied the default config however I then got greeted by less then ideal errors (mostly `Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
`). By eliminating most of the config I quickly found out it was due to incorrect font paths. 

I think rwaybar could be made easier with better error handling. In the source I saw you bubble errors up using `Box<dyn Error>`. I have found [color_eyre](https://docs.rs/color-eyre/latest/color_eyre/) a wonderfull (drop in!) replacement for that. It would make it easy to add context to an error such as the one above.

For example the font not found line: https://github.com/danieldg/rwaybar/blob/a8425f475e3d56271880f4b853eb81aef2133325/src/font.rs#L27

could become:
```rust
use color_eyre::{Result, eyre::WrapErr};
pub fn new(name: String, path: PathBuf) -> Result<Self> {
    let file = File::open(&path)
        .wrap_err_with(|| format!("Could not open font {name} at given path {path:?}"))? 
```

**Comment by danieldg** [comment]
I have tried to make errors that actually happen trigger `error!` instead of the `Box<dyn Error>` path; font errors in particular should do that.  It looks like I didn't think through that error path well.
