### ISSUE TITLE
Project name suggestions

### ISSUE THREAD

**Issue by uni-dos** [danieldg/rwaybar#4]
I stumbled upon this project through GitHub and am very happy to see a bar that doesn't depend on gtk. The name, to me, just doesn't roll of the tongue well. I have some suggested names wraybar, raybar, or rubar. This is just a suggestion and not a really productive one. (I don't know rust)

**Comment by dvdsk** [comment]
You could take waybar-rs if you want to emphasize its in rust. Or maybe waybarr. I must say I like rubar :)

**Comment by uni-dos** [comment]
Waybar-rs does make sense as well but I don't think a project name has much of a priority. Rubar was also one of my favorites.
