### ISSUE TITLE
Publish `pulse_tokio` module on crates.io / upstream the tokio support?

### ISSUE THREAD

**Issue by MaxVerevkin** [danieldg/rwaybar#6]
Hi!

Would you consider publishing `pulse_tokio` module on crates.io? Or maybe it would be possible to [upstream it](https://github.com/jnqnfe/pulse-binding-rust/issues/20)?

Thanks!

**Comment by danieldg** [comment]
I think I'll want to make it threadsafe before doing that, but it's a good idea.

**Comment by MaxVerevkin** [comment]
Since there hasn't been any progress upstreaming it, are you still interested in publishing it?

**Comment by danieldg** [comment]
Just published it; future discussion should probably be at https://github.com/danieldg/pulse-binding-rust (note that I never did get around to making it thread-safe, for one).
